### PR TITLE
Resolve api_key_vault_cmd like wakatime-cli does

### LINKED ISSUE #374: `api_key_vault_cmd` configuration option for shell command to get api key from vault fails with ENOENT
The `api_key_vault_cmd` configuration option which according to https://github.com/wakatime/wakatime-cli/blob/develop/USAGE.md can be used to specify a _"shell command to get api key from vault"_ fails for me, on Linux, for example for a simple test like this in `.wakatime.cfg`:

```
api_key_vault_cmd = /usr/bin/echo hi
```

I'm getting this in the VSC Developer Tools:

```
ERR spawn /usr/bin/echo hi ENOENT: Error: spawn /usr/bin/echo hi ENOENT
	at ChildProcess._handle.onexit (node:internal/child_process:283:19)
	at onErrorNT (node:internal/child_process:476:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

I'm intentionally opening this as a separate bug from #295 which seems to be Windows with specific restricted policy.

This is with `WakaTime.vscode-wakatime@24.4.0` (from `code --list-extensions --show-versions`).

### PR DESCRIPTION
**Pull request by kisaragi-hiu**
This package was treating the entire config value of `api_key_vault_cmd` as one executable name, rather than treating it as a shell command --- but it also probably shouldn't treat it as a shell command, as wakatime-cli doesn't do that either.

wakatime-cli instead treats the value as a space-separated list of the executable and its arguments:

https://github.com/wakatime/wakatime-cli/blob/1fd560a/cmd/params/params.go#L707-L719

This PR makes vscode-wakatime mimick that behavior.

This should fix https://github.com/wakatime/vscode-wakatime/issues/387.

### CODE REVIEW

**Comment by gandarez** [comment]
It looks good to me, wdyt @alanhamlett?

File: src/options.ts [hunk 1]
```diff
@@ -239,11 +239,21 @@ export class Options {
...
+      // Use basically the same logic as wakatime-cli to interpret cmdStr
+      // https://github.com/wakatime/wakatime-cli/blob/1fd560a/cmd/params/params.go#L697
+      let cmdStr = await this.getSettingAsync<string>('settings', 'api_key_vault_cmd');
+      if (!cmdStr) return '';
+
+      cmdStr = cmdStr.trim();
+      if (cmdStr === '') return '';
+
+      const cmdParts = cmdStr.split(" ");
+      if (cmdParts.length === 0) return '';
```
Comment (alanhamlett) [inline src/options.ts:251]: This isn't possible, because of the previous `.trim()` and return early if empty. However, let's merge it and I'll fix on main branch.

**Review by alanhamlett — APPROVED** [review]
